FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=northwind
ENV MYSQL_USER=northwind
ENV MYSQL_PASSWORD=northwind

# Copy initialization scripts
COPY mysql-init/ /docker-entrypoint-initdb.d/

EXPOSE 3306